name: Toast MATLAB MEX

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build_mex:
    name: Build MEX on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3

      # Get MATLAB
      - name: Set up MATLAB (R2023b for Apple Silicon)
        if: matrix.os == 'macos-14'
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b

      - name: Set up MATLAB (R2022a)
        if: matrix.os != 'macos-14'
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2022a

      # Build the MEX
      - name: Build
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              export CC=gcc-10
              export CXX=g++-10
          fi
          mkdir build
          cd build
          cmake ../
          cmake --build . --target install --config Release

        
      - uses: actions/upload-artifact@v3
        with:
          name: toastmm-matlab-${{ runner.os }}-${{ runner.arch }}
          path: |
            dist/matlab
            
