name: Toast MATLAB MEX

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build_mex:
    name: Build MEX on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      # Get MATLAB
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Build the MEX
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../
          cmake --build . --target install --config Release

      - uses: actions/upload-artifact@v3
        with:
          name: toastmatlab-${{ runner.os }}
          path: |
            dist/matlab
            