name: Toast Python Wheel

on: [pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.5.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir ./dist/python

      - uses: actions/upload-artifact@v3
        with:
          name: pytoast-${{ runner.os }}
          path: |
            dist/python/*.whl
            dist/python/examples
            dist/python/meshes