name: Toast Python Wheel

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir ./dist/python

      - uses: actions/upload-artifact@v4
        with:
          name: toastmm-python-${{ runner.os }}-${{ runner.arch }}
          path: |
            dist/python/*.whl
            dist/python/examples
            dist/python/meshes
