name: Toast Library Tests

on:
  push:
    branches: [master]

jobs:
  build_mex:
    name: Build library on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      # Build the MEX
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../
          cmake --build . --target install --config Release

      - name: Test
        run: |
          cd ../test
          make
